function(set_process_timing_source_files_properties)
    get_target_property(files process_timing INTERFACE_SOURCES)
    foreach(file IN LISTS files)
        get_filename_component(file_path_dir ${file} DIRECTORY)
        if(file_path_dir MATCHES "[.]*[/\\]process_timing")
            source_group("process_timing" FILES ${file})
        endif()
    endforeach()
endfunction(set_process_timing_source_files_properties)
